### ISSUE TITLE
Offer HTML5 with RDF(a) via styled templates

### ISSUE THREAD

**Issue by acka47** [rightsstatements/rights-app#1]
Offer HTML5 with RDFa representations via this URI pattern:

`/page/$id/$version/[?$parameter=$value][&$parameter=$value]`

Examples:

- `/page/InC/1.0/`
- `/page/InC/1.0/?language=es` 
- `/page/NoC­CR/1.0/?language=nl&relatedURL=http://example.com/x`

**Comment by anarchivist** [comment]
Documentation from @paulkeller2 on the content for the HTML representations for the entire vocab and the collections: https://docs.google.com/document/d/1VgetlDFjxtPhlR1FSmouVhcfxu3UZ3jaQkvGLjCB6Ns/edit#heading=h.s3wpaysgs5ri

**Comment by anarchivist** [comment]
@ryanjunell Can you upload the comps for the statement page here?

**Comment by anarchivist** [comment]
Comp for the individual rights statements pages. 
![deed v9b](https://cloud.githubusercontent.com/assets/73732/13962626/11268de4-f01f-11e5-939b-a44452435a89.png)

**Comment by mzeinstra** [comment]
Independently confirmed by Paul that this is indeed final and can be implemented. 

@ryanjunell I believe it appropriate to share the source files of this document and other technical details like fonts, font-size, colors, etc.

**Comment by literarymachine** [comment]
Discussing this with @j0hj0h, we were wondering why the individual statement pages are lacking the navigation which, according to the [documentation](https://docs.google.com/document/d/1VgetlDFjxtPhlR1FSmouVhcfxu3UZ3jaQkvGLjCB6Ns/edit#heading=h.s3wpaysgs5ri) are present on all other pages (static pages, collections, vocab)?

**Comment by mzeinstra** [comment]
I believe this is intentional, as the people coming to this page should not be interested in the other statements. People who are interested in the entire project can navigate to the main page using the link on the page.

**Comment by ryanjunell** [comment]
the statement pages are considered "stand-alone"

**Comment by literarymachine** [comment]
Must have overlooked that when reading the documentation:

> All rights statement pages do not have a navigation bar, the only navigation element is a link to the homepage at the bottom of the statement.

Sorry.

**Comment by ryanjunell** [comment]
@literarymachine I have a dozen screenshots of approved design for the website... shall I post them all here? the screens would not be useful for pulling bitmaps for the site. I can export appropriate sized graphics like the logo, icons, and statement banners. I can also help set styles.

**Comment by literarymachine** [comment]
@ryanjunell assuming that most of these are screenshots for the website, not the "app", rightsstatements/rightsstatements.github.io#6 would be the place to put them. Also, do you have them as PSD or something alike? From the Slack discussion I take it that [Gotham Screensmart](http://www.typography.com/fonts/gotham/styles/screensmart/) is the font, but I did not find font sizes etc.

**Comment by ryanjunell** [comment]
I have an illustrator file. I will post font sizes. I can assist in setting styles once the framework is established.

**Comment by anarchivist** [comment]
Collection and vocab styles can be found in https://github.com/rightsstatements/rightsstatements.github.io/issues/6#issuecomment-202924895
