### ISSUE TITLE
What are valid/invalid interaction patterns for the "relatedURL" parameter?

### ISSUE THREAD

**Issue by acka47** [rightsstatements/rights-app#11]
`relatedURL` is listed as valid parameter for the HTML request of three rights statements: InC­OW­EU, NoC­CR, NoC­OKLR. But, as far as I can see, the valid and invalid interaction patterns for the `relatedURL` parameter are not specified in the [white paper](http://rightsstatements.org/files/151002requirements_for_the_technical_infrastructure_for_standardized_international_rights_statements.pdf). On p. 6 it reads (my emphasis):

> The URI for human­-readable representations of specific rights statements MAY include an additional query string parameter to display additional information. These parameters are only valid when used in the URI for a human­readable representation. These parameters MUST NOT be used as part of rights statement URIs or in URIs for machine­readable representations. A parameter listed for a given rights statement in the table below  MUST be used only for the purpose indicated for a given rights statement vocabulary term. Parameters for additional metadata  MUST NOT be used in combination with any rights statement not included in the table below; otherwise, it is considered an  invalid use of that parameter. _The behaviour of the interaction patterns between a client and a server in cases of valid and invalid use of parameters is described in the “HTTP interaction patterns” subsection of the “Publication and implementation” section below_. 

In the “HTTP interaction patterns” subsection of the “Publication and implementation” section only patterns for the `date` parameter but not for the `relatedURL` parameter can be found.

@anarchivist, @no-reply, @kestlund, @musebrarian: Did I miss something or is the pattern specification indeed missing?

**Comment by no-reply** [comment]
@acka47 Hoping I'm understanding your question correctly...

The interaction patterns given for the `date` parameter are intended as examples applying to both/all parameters.

The short version is that parameters are `406 Not Acceptable` for all but the `page` URIs for the applicable statements.  Requests to the `vocab` or `data` URI for statements that can accept a parameter use `Alternates:` headers to direct the client toward the relevant `page` (retaining the parameter) or `vocab` (omitting it) resource.

Does that help?

**Comment by acka47** [comment]
@no-reply Thanks. It helps, as it confirms what I was thinking regarding the HTTP patterns.

In fact, I should have phrased the title and wording differently to address my main question regarding the _HTML_ that still is in parts open: How should the HTML be adjusted if one of the parameters has been given in a valid manner. After looking again at the ["Recommendations for Standardized International Rights Statements"](http://rightsstatements.org/files/151002recommendations_for_standardized_international_rights_statements.pdf), I now understand what to do for the `relatedURL` parameter with respect to the three statements that allow it. But I can not see how to exactly handle the `date` parameter within the HTML. The snippet in https://cloud.githubusercontent.com/assets/160292/11157010/653503ce-8a4f-11e5-8d7f-63d11a4cf445.png doesn't give much clarity and the white papers also leave this open as far as I can see.

**Comment by no-reply** [comment]
@anarchivst can you confirm my recollection that the `date` parameter was removed from the Statements whitepaper after the release of the Technical paper? If so, does this mean that @acka47 and @literarymachine need not worry about implementing it?

**Comment by anarchivist** [comment]
I think the answer is that we don't need to worry about implementing `date` for `OOC-NC` for the time being. I'd forgotten that I'd opened rightsstatements/data-model#26 shortly before the publication of the white papers since the "extra metadata" for that statement was removed. 

I asked Paul for any updates, and unfortunately there are none yet. We may need to support it in the future. I'll follow up once I have more information.

**Comment by acka47** [comment]
Closing this for now.
