### ISSUE TITLE
Dereference vocabulary URI, requesting JSON-LD

### ISSUE THREAD

**Issue by acka47** [rightsstatements/rights-app#14]
Before we have clarified #12, serve the whole SKOS scheme (as JSON-LD).

**Comment by acka47** [comment]
Acceptance criteria:

For the following requests:
- `curl -H "Accept: application/ld+json" http://rightsstatements.org/vocab/1.0/`
- `curl -H "Accept: application/json" http://rightsstatements.org/vocab/1.0/`

deliver https://raw.githubusercontent.com/rightsstatements/data-model/master/rights-statements.ttl *in JSON-LD serialization*.

**Comment by acka47** [comment]
Acceptance criteria:

For the following requests:
- `curl -H "Accept: application/ld+json" http://rightsstatements.org/vocab/1.0/`
- `curl -H "Accept: application/json" http://rightsstatements.org/vocab/1.0/`

server responds:

303 See Other
Location: http://rightsstatements.org/data/1.0.jsonld

**Comment by literarymachine** [comment]
@acka47 are you sure the `Location` is supposed to include the extension? If dereferencing the vocabulary follow the same pattern as dereferencing an individual statement (see [requirements, p. 20](http://rightsstatements.org/files/151002requirements_for_the_technical_infrastructure_for_standardized_international_rights_statements.pdf)), the `Location` would be `http://rightsstatements.org/data/1.0/`.

**Comment by acka47** [comment]
Oups, you are right. Will edit the acceptance criteria accordingly.

**Comment by anarchivist** [comment]
If you look at p. 16, there's a **SHOULD** specified under "Requesting Specific Representations":

> The `Content-­Location` header SHOULD be used to allow a generic machine-­readable representation URI to refer to the URI for a specific machine-­readable representation. URIs for each specific machine­-readable representation SHOULD be linked from the human­-readable representation (e.g. links to download Turtle­-serialized RDF can be obtained using the pattern `.../data/x.x/statement.ttl`).

**Comment by acka47** [comment]
As @anarchivist writea, the extension is included in the Content-Location header when someone e.g makes a GET on `http://rightsstatements.org/data/1.0/` requesting turtle. I don't have covered this Content-Location requirement in any acceptance criteria, yet. With the current approach of separating "dereference" and "offer" issues, I actually don't know where to best put it... Will think about it and maybe make a generic issue for this requirement.
