### ISSUE TITLE
Which file extension to use for ld+json?

### ISSUE THREAD

**Issue by acka47** [rightsstatements/rights-app#25]
The example on page 5  of the technical white paper (`/data/NoC­CR/1.0.json` ) suggests that `.json` should be used. In the [IANA registration for the media type "application/ld+json" ](https://www.iana.org/assignments/media-types/application/ld+json) `.jsonld` is named as file extension. Currently, one can find both versions in the rights-app issues.

We should clarify which extension should be used by the rightsstatement application: `.json` or `.jsonld`?

**Comment by anarchivist** [comment]
I'm :+1: on allowing *both* `.json` and `.jsonld`. CC @no-reply @aisaac

**Comment by acka47** [comment]
If we allow both, we still will have to decide where to link to in the HTML and in the Content-Location header.

**Comment by no-reply** [comment]
:+1: to both; treating `.json` as the canonical link, following e.g. IIIF.

**Comment by aisaac** [comment]
How about allowing both extensions *and* media types.
application/ld+json with .jsonld
application/json with .json
The content of the file served would be the same of course, which would make it only a minor change to our original spec (and one that avoids long discussions about the matter :-) )

**Comment by aisaac** [comment]
Important point: this is being proposed while @no-reply is actually in my office :-)

**Comment by no-reply** [comment]
:+1:, but in that case, I think we want to use `.jsonld` when linking, in general.  Some parsers may not like the `application/json` media-type (notably, it is not supported by Ruby-RDF's [`Reader#for(media_type)` interface](https://github.com/ruby-rdf/json-ld/blob/develop/lib/json/ld/format.rb#L24-L26)).

**Comment by anarchivist** [comment]
Agreed with @no-reply and @aisaac.

**Comment by acka47** [comment]
Resolved. Closing.
