### ISSUE TITLE
What to serve for a GET on a /data URI without Accept header?

### ISSUE THREAD

**Issue by acka47** [rightsstatements/rights-app#32]
Currently making a GET on a /data URI gives a 406, see https://github.com/rightsstatements/rights-app/pull/30#issuecomment-161512407. As far as I know, the behaviour for this situation isn't specified in the white paper.
@literarymachine suggests serving JSON-LD as default and is pushing this change to the dev server.

Would this be OK with the working group?

**Comment by no-reply** [comment]
Defaulting to either JSON-LD or Turtle is good. Factors that might differentiate between the two:

  - Is the full context included in JSON-LD responses? The default response should fully encode the graph without need for a second request or cache of the context.
  - Is there a notable size difference in the serializations?

Unless one of those seems to favor Turtle heavily, :+1: to JSON-LD.

**Comment by literarymachine** [comment]
> Is the full context included in JSON-LD responses? The default response should fully encode the graph without need for a second request or cache of the context.

Yes, the full `@context` is included.

> Is there a notable size difference in the serializations?

Currently 22K ttl vs. 26K json for the full vocab.

Assuming this is OK, will leave as is (see https://github.com/rightsstatements/rights-app/pull/30#issuecomment-162533720).

**Comment by no-reply** [comment]
Sounds good. Closing this. @anarchivist or @aisaac (or anyone else) can reopen if this isn't a satisfactory conclusion.

**Comment by anarchivist** [comment]
:+1: This sounds good to me as well.
