### ISSUE TITLE
Point to /data or /vocab URI for recovery guidance?

### ISSUE THREAD

**Issue by acka47** [rightsstatements/rights-app#34]
From https://github.com/rightsstatements/rights-app/pull/33#issuecomment-164290114.

When somebody uses a parameter – which are only allowed on _some_ `/page` URIs – on a `/vocab` URI the desired server behaviour isn't consistently shown in the technical white paper.
In the current implementation, besides pointing to the `/page` URL+parameter also the `/data` URI is listed in the `Alternates` header along with the document format. This conforms to two images ([here](https://cloud.githubusercontent.com/assets/160292/11157042/8f83bf1c-8a4f-11e5-8deb-594b63a4e632.png) and [here](https://cloud.githubusercontent.com/assets/160292/11157089/d43093ce-8a4f-11e5-9d8c-5897aa1812d1.png)) in the white paper.

But there is one [image](https://cloud.githubusercontent.com/assets/160292/11157054/a1c322c6-8a4f-11e5-91d1-ad2caee951c4.png) on page 23 of the technical white paper that suggests rather pointing to the `/vocab` URI without indicating a document format. How should it actually be implemented:

1. point to `/page` and `/data`
2. point to `/page` and `/vocab` or 
3. point to all three URIs `/page`, `/data` and `/vocab`, e.g.:

```
Alternates: {"/page/InC-OW-EU/1.0/?relatedURL=http://example.org/" 0.9 {text/html}},{"/data/InC-OW-EU/1.0/" 0.9 {text/turtle},{"/vocab/InC-OW-EU/1.0/" 0.9}
```
?

**Comment by acka47** [comment]
As discussed in the meeting: We will include all supported document formats for a `/data` URI in the `Alternates` header.

**Comment by anarchivist** [comment]
Example response:

```
$ curl -v "http://h2481931.stratoserver.net:9001/vocab/InC-OW-EU/1.0/?relatedURL=http://example.org/"
> GET /vocab/InC-OW-EU/1.0/?relatedURL=http://example.org/ HTTP/1.1
> User-Agent: curl/7.35.0
> Host: h2481931.stratoserver.net:9001
> Accept: */*
> 
< HTTP/1.1 406 Not Acceptable
< Alternates: {"/vocab/InC-OW-EU/1.0/" 0.9},{"/page/InC-OW-EU/1.0/?relatedURL=http://example.org/" 0.9 {text/html}},{"/data/InC-OW-EU/1.0/" 0.9 {text/turtle},{"/data/InC-OW-EU/1.0/" 0.9 {application/ld+json},{"/data/InC-OW-EU/1.0/" 0.9 {application/json}}
< Date: Fri, 11 Dec 2015 13:14:01 GMT
< Content-Length: 0
```

**Comment by anarchivist** [comment]
I believe this is resolved. @acka47 @literarymachine can you confirm?

**Comment by acka47** [comment]
Yes, it's resolved. Closing.
