### ISSUE TITLE
Encoding mismatch between locale files and Turtle leads to display issues

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rights-app#65]
In adding the changes for the German locale in #64, I noticed that there seems to be a mismatch between the expected encoding between the Turtle source (UTF-8) and the locale files. (The branch of the vocabulary repo with the German translation is [`de-translation`](https://github.com/rightsstatements/data-model/tree/de-translation).) The screenshot below demonstrates the issue, with text from the locale file (`messages_de.properties`) indicated within the magenta boxes.

I'm guessing that this is because Java properties files are expected to be ISO 8859-1, while the text in the PR is UTF-8. Is there a way to make this consistent given that we may have languages that might not be easily expressed in ISO 8859-1, and since the Turtle will always be UTF-8?

![screen shot 2018-05-29 at 4 32 27 pm](https://user-images.githubusercontent.com/73732/40691165-78fb5ade-635f-11e8-8b2a-30267664ff88.png)

**Comment by literarymachine** [comment]
> I'm guessing that this is because Java properties files are expected to be ISO 8859-1, while the text in the PR is UTF-8.

Correct!

> Is there a way to make this consistent given that we may have languages that might not be easily expressed in ISO 8859-1, and since the Turtle will always be UTF-8?

We are currently using [Handlebars.java i18n](https://github.com/jknack/handlebars.java#i18n) which is based on loading properties files with the default Properties loader. While there are ways to use a [custom ResourceBundle.Control](https://stackoverflow.com/a/4660195) in general, I'd have to check how/if that is supported by Handlebars.java. Have you considered using a platform such as https://crowdin.com/ for localization? They don't support turtle, but work well with `.properties` files and convert them to ISO 8859-1 transparently (using Unicode escapes for unsupported characters).

**Comment by anarchivist** [comment]
Thanks @literarymachine - while clunky for now, Unicode escapes are enough to get this over the threshold for the German translation. I'll create a new issue to investigate a custom ResourceBundle.Control
