### ISSUE TITLE
Vocab and collection pages are not localized even when translated pages exist

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rights-app#66]
In testing #64, I noticed that the human-readable pages for the entirety of the vocabulary and for the individual collection pages are not being localized, even when there is a corresponding translated page. (See the Jekyll site repo; the `de-translation` branch contains the changes to be merged in rightsstatements/rightsstatements.github.io#132). 

![Screenshot](https://user-images.githubusercontent.com/73732/40691529-28e41e76-6361-11e8-94e7-1728b11ef701.gif)

**Comment by paul2keller** [comment]
@anarchivist is there somewhere i can take a look at the DE translation myself?

**Comment by anarchivist** [comment]
Not yet, no. The changes have not been merged and are thus not deployed.

**Comment by paul2keller** [comment]
ok, another question: can we display separate language versions of the graphics depending on the language?

**Comment by anarchivist** [comment]
It may be possible (with some minor changes), but we don't have translated versions of the graphics.

**Comment by paul2keller** [comment]
yeah, but it looks quite shitty with the untranslated graphics. i can go after translated graphics. are these taken from a central location and resized on when displaying the pages or are these made to size image files?
