### ISSUE TITLE
Investigate custom ResourceBundle.Control with Handlebars to allow for consistent use of UTF-8 

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rights-app#68]
@literarymachine pointed out while trying to resolve #64:

> We are currently using [Handlebars.java i18n](https://github.com/jknack/handlebars.java#i18n) which is based on loading properties files with the default Properties loader. While there are ways to use a [custom ResourceBundle.Control](https://stackoverflow.com/a/4660195) in general, I'd have to check how/if that is supported by Handlebars.java. Have you considered using a platform such as https://crowdin.com/ for localization? They don't support turtle, but work well with `.properties` files and convert them to ISO 8859-1 transparently (using Unicode escapes for unsupported characters).

(We probably want to have a separate thread about looking at streamlining the translation workflow but this a good point to raise.)

**Comment by anarchivist** [comment]
Closed on 21 November 2018; presumption that localization platforms will address this.

**Comment by aisaac** [comment]
And considering that @anarchivist will write documentation about updating translations the right way :-)
