### ISSUE TITLE
Language tags with hyphenated subtags are not loading translations as expected

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rights-app#75]
rightsstatements/data-model#64 added Finland-Swedish (`sv-FI`) to the Turtle, and rightsstatements/rightsstatements.github.io#162 adds the translations to the website. If I modify `application.conf` to indicate that `sv-FI` is a supported language, and go to the URL for of the individual statement pages, the English translation loads instead.

**Comment by literarymachine** [comment]
Will look into this next week as I am out of office until then!
