### ISSUE TITLE
New statement needed for European Out-Of-Commerce works

### ISSUE THREAD

**Issue by mzeinstra** [rightsstatements/rights-app#94]
Dear all,

It's been a while since I've been involved in this project. So I don't know if this is the right place for this request.

On june 7th 2021 the European Intellectual Property Office opened a new database for the registration of Out-Of-Commerce works. Basically when works, fitting the criteria, have been registered for more than 6 months in the database they can be displayed online without having the need for permission.

This needs its own statement. Is the consortium working on this, and can I join that work?

Kind regards,

Maarten Zeinstra

**Comment by anarchivist** [comment]
Hi @mzeinstra - this issue tracker isn't the best way to inquire about that. Please send an email to info@rightsstatements.org instead. I'll pass along word to other folks on the consortium however.

**Comment by mzeinstra** [comment]
Thanks Mark, will do!

**Comment by anarchivist** [comment]
Closing here; should be taken up by the Statements Working Group
