### ISSUE TITLE
Collection pages does not link properly to statement pages.

### ISSUE THREAD

**Issue by mzeinstra** [rightsstatements/rights-app#97]
https://rightsstatements.org/page/InC/1.0?/language=en gives an error

**Comment by literarymachine** [comment]
I believe you have mistyped the URL. It should be https://rightsstatements.org/page/InC/1.0/?language=en which works.

**Comment by mzeinstra** [comment]
Interesting, I thought I got there by using a link on a page on rightsstatements.org.

Cannot reproduce anymore. closing.

**Comment by mzeinstra** [comment]
This was bugging me, I clicked around some more, and found it:

Steps to reproduce:

1. go to https://rightsstatements.org/page/1.0/?language=en
2. click on the H3 "In Copyright" see the screenshot attached
![Screenshot 2022-05-17 at 10 17 55](https://user-images.githubusercontent.com/5627431/168764346-779b62d2-24ab-47f7-9555-148a6c945031.png)

**Comment by mzeinstra** [comment]
and pull request: https://github.com/rightsstatements/rightsstatements.github.io/pull/286

**Comment by anarchivist** [comment]
Thanks for the fix, @mzeinstra.
